import { Dish } from "./dish";

export const DISHES: Dish[] = [
  new Dish("Frytki", "międzynarodowa", ["dodatek", "przystawka"], ["ziemniaki", "olej", "sól"], 9, 12, "Popularny dodatek do dania.", ["https://drive.google.com/uc?export=view&id=1WIUPfAcLX3w61o0_VTuiOxj8mVzXjSXy", "https://drive.google.com/uc?export=view&id=1FXoVut20vA9AiUkRzK9D23YDVbLZCEWF", "https://drive.google.com/uc?export=view&id=141OUMxPJHILPWZMLqkoz9xgJl_M4E0Mj"]),
  new Dish("Pizza Margherita", "włoska", ["wegański", "dania główne", "kolacja"], ["mąka", "drożdże", "ser"], 24, 7, "Najpopularniejsza pizza na świecie!", ["https://drive.google.com/uc?export=view&id=1Ga44syHNZsPVdFpMUIyjK_ykBeq04RsM", "https://drive.google.com/uc?export=view&id=1Ma1bBFhCC9NoRQQL42dIz963UrGX95HI", "https://drive.google.com/uc?export=view&id=1WT8QmZw-c1lNcWG9p_eOvLWgtiySs1wE"]),
  new Dish("Pierogi ruskie", "polska", ["wegański", "dania główne"], ["ziemniaki", "twaróg", "mąka"], 11, 29, "Super polskie pierożki.", ["https://drive.google.com/uc?export=view&id=1IwzOb1SfwdngIqE9gFBFIOYSd7PDB4Uo", "https://drive.google.com/uc?export=view&id=1-8U9ZrvGmNhq0nt2QbdTyrj8L9twGaPF", "https://drive.google.com/uc?export=view&id=1bB_AJjDc5EHjWjS4DhIoW2n3uWxrr-n8"]),
  new Dish("Jaja Benedykta", "amerykańska", ["przystawka", "śniadanie"], ["jajka", "ocet z białego wina", "wędlina"], 5, 20, "Ekskluzywna potrawa trudna do przygotowania.", ["https://drive.google.com/uc?export=view&id=1Zc_odYxsB-96mQJ7WfKcyMllWB9sWenu", "https://drive.google.com/uc?export=view&id=15Yd_oYhK3RQLFtuHgB96O2JByMDG7QVh", "https://drive.google.com/uc?export=view&id=1YpqBbbxf2zTeUOssm0QJk6O0C6M3n6Qz"]),
  new Dish("Suflet", "francuska", ["wegański", "deser"], ["jajka", "mąka", "cukier"], 4, 30, "Ekstrawagancki deser!", ["https://drive.google.com/uc?export=view&id=1zrQYy3YQ0Vs47oajMZiqVgWmMVMFjGzp", "https://drive.google.com/uc?export=view&id=1eplI1WgPdGpLwCBYhMJQrH5gpw2vmVLW", "https://drive.google.com/uc?export=view&id=1SODaV1t9wf38cR4H3zd9x3J82Jsvn1tA"]),
  new Dish("Rib Eye Steak", "amerykańska", ["mięsny", "dania główne"], ["stek z antrykotu", "olej", "sól"], 13, 54, "Ale mięsko!", ["https://drive.google.com/uc?export=view&id=1_W17DschWLVeRBQSf4ZtFMZz3o7OMWeb", "https://drive.google.com/uc?export=view&id=12NsB3aYy41tBRd6ZEfpmDj5YrMMmuEsg", "https://drive.google.com/uc?export=view&id=19-TR9Ia_5-fPaVDPfsOlbqYU-tmtoEkh"]),
  new Dish("Cezar", "międzynarodowa", ["sałatka", "przystawka"], ["sałata rzymska", "grzanki", "parmezan"], 19, 16, "Świetna sałatka.", ["https://drive.google.com/uc?export=view&id=1r9Cs1VAZWJ-CgYpKf9p7oZnuBQMz8lJa", "https://drive.google.com/uc?export=view&id=1fg_ZGPsRgdCWjPrFzTOK_ktlE8wiXj_N", "https://drive.google.com/uc?export=view&id=1_0lJn3PTr5oTPkDhwYQVwRpNK2r2fRFF"]),
  new Dish("Rosół", "polska", ["zupa"], ["kura", "marchewki", "cebula"], 8, 17, "Super zupka!", ["https://drive.google.com/uc?export=view&id=1DBrIKT7fsw-ZQbXzk0Enwi8Pj3h_uIZj", "https://drive.google.com/uc?export=view&id=1mCmwuxKCjxiFulOxeIjU7cGd8B6DFQfp", "https://drive.google.com/uc?export=view&id=1E9GVYUh5RIrozCmVo5Ugy_2_4rJ7JkgY"])
]
